package:
  name: pyfftw
  version: {{ GIT_DESCRIBE_TAG }}

source:
  #git_rev: v0.13.1
  git_url: https://github.com/pyFFTW/pyFFTW.git

build:
  script: python setup.py install

requirements:
  build:
    - python
    - fftw
    - numpy
    - cython
    #- setuptools
  run:
    - python
    - fftw
    - numpy

test:
  imports:
    - pyfftw

about:
  home: https://github.com/pyFFTW
  license: GPL
  license_file: license.txt