package:
  name: enum-compat
  version: !!str 0.0.2

#build:
#  noarch_python: True

requirements:
  build:
    - python
    - pip

  run:
    - python

about:
  home: https://bitbucket.org/al45tair/netifaces
  license: MIT License
  summary: Portable network interface information.
