package:
  name: enum-compat
  version: !!str 0.0.2

#build:
#  noarch_python: True

source:
  path: ./enum-compat/

build:
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

about:
  home: https://bitbucket.org/al45tair/netifaces
  license: MIT License
  summary: Portable network interface information.
