package:
  name: netifaces
  version: 0.10.9

source:
  git_rev: release_0_10_9
  git_url: https://github.com/al45tair/netifaces

build:
  script: python setup.py install

requirements:
  build:
    - python
    - cython #easy way of making sure we have a c compiler - FIXME

  run:
    - python

about:
  home: https://github.org/al45tair/netifaces
  license: MIT License
  summary: Portable network interface information.
