package:
  name: dispatch
  version: 1.0

source:
  #git_rev: v0.13.1
  git_url: https://github.com/olivierverdier/dispatch.git

build:
  script: python setup.py install

requirements:
  build:
    - python
    #- setuptools
  run:
    - python

test:
  imports:
    - dispatch

about:
  home: github.com/olivierverdier/dispatch
  license: BSD
  license_file: license.txt