package:
  name: ifaddr
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/pydron/ifaddr


build:
  noarch_python: True
  preserve_egg_dir: False

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python


about:
  home: https://github.com/pydron/ifaddr
  license: MIT
  summary: 'ifaddr - Enumerate IP addresses on the local network adapters'
