#recipe copied from conda-forge

{% set name = "ifaddr" %}
{% set version = "0.1.7" %}
{% set sha256 = "1f9e8a6ca6f16db5a37d3356f07b6e52344f6f9f7e806d618537731669eb1a94" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - ifaddr

about:
  home: https://github.com/pydron/ifaddr
  license: MIT
  license_family: MIT
  #license_file: LICENSE.txt
  summary: 'Python Library to enumerate all network interfaces '
  doc_url: https://pythonhosted.org/ifaddr/
  dev_url: https://github.com/pydron/ifaddr
