# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build Installers

on:
  workflow_dispatch:

jobs:

  conda_pkgs:
    strategy:
      matrix:
        os: [windows-latest, ] # macos-latest], ubuntu-latest]
        python: ['3.6', ] #,2.7] - # 2.7 disabled for now due to missing VC9

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python }}
    - name: Conda info
      run: |
        conda info
        conda list
    - name: Build and publish
      shell: pwsh
      env:
        D_USERNAME: ${{ secrets.DOCS_USERNAME }}
        D_PASSWORD: ${{ secrets.DOCS_PASSWORD }}
      run: |
        conda install constructor
        cd ./installers
        constructor .
        echo $D_USERNAME
        $files = Get-ChildItem ./*.exe
        foreach ($file in $files) {echo "uploading $file ..."; curl.exe -v -u "${D_USERNAME}:${D_PASSWORD}" -T $file.FullName https://python-microscopy.org:2078/}
