# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build Conda packages

on:
  workflow_dispatch:

jobs:

  conda_pkgs:
    strategy:
      matrix:
        os: [ubuntu-latest, ] #windows-latest, macos-latest]
        python: ['3.6', ] #,2.7] - # 2.7 disabled for now due to missing VC9

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python }}
    - name: Conda info
      run: |
        conda info
        conda list
    - name: Install dependencies
      run: |
        conda install conda-build
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        conda build --skip-existing toposort pyfftw dispatch pymecompress mpld3 ifaddr zeroconf pyme-depends
        conda build --skip-existing python-microscopy
        #python setup.py bdist_wheel
        #twine upload --skip-existing dist/*